services:
  phpserver:
    image: php:7.2-apache
    volumes:
      - ./www:/var/www/html
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhadoroot
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
